name = "vpnkeygen"
main = "index.ts" # ğŸ‘ˆ á€’á€«á€€ á€á€„á€·á€º Worker script á€˜á€šá€ºá€™á€¾á€¬á€›á€¾á€­á€œá€²á€†á€­á€¯á€á€¬ Wrangler á€€á€­á€¯ á€•á€¼á€±á€¬á€á€¬á€•á€«
compatibility_date = "2025-11-25"
